### ISSUE TITLE
resp.subscriptions is not iterable

### ISSUE THREAD

**Issue by carlmiller99** [graanco/homebridge-SimpliSafePlatform#10]
thought i had it working but now it throws this error which interrupts the process. interestingly, i see this after it successfully refreshes the sensors multiple times.

TypeError: resp.subscriptions is not iterable
    at API.get_system (/usr/lib/node_modules/homebridge-simplisafeplatform/client/api.js:230:36)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async API.get_Alarm_State (/usr/lib/node_modules/homebridge-simplisafeplatform/client/api.js:317:12)
(node:1926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/homebridge-simplisafeplatform/index.js:236:32
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

anyone else seeing this?

**Comment by kitknox** [comment]
I am having the same issue after it has been running and working for a bit.  Restarting homebridge temporarily fixes everything before it ends up failing again.

**Comment by graanco** [comment]
I notice this issue too. After an hour of operating it seems like the refresh token isn't working... I am bring the code more toward the simply---plython version instead of the API from SimpliSafe. I will test it again today and see on how it works...

**Comment by graanco** [comment]
okay I think I am going to remove SS2 or less support... The delay is causing a response issue. Also I will be setting it up so there is a 30 second delay for the alarm unless I can get the push working from socket.io

**Comment by graanco** [comment]
This issue should be gone now.
