### ISSUE TITLE
Accessories Dont Update

### ISSUE THREAD

**Issue by nikonratm** [graanco/homebridge-SimpliSafePlatform#11]
OS: Raspbian GNU/Linux 10 (buster)
Homebridge: 0.4.50
Node: v12.6.0

Out of the box all of my accessories showed up but none seem to update e.g. when a window is open the contact sensor still showed closed. In digging into it, seems there are a few errors in the code that prevent updating of accessories. I'll create a PR, but specifically:

https://github.com/graanco/homebridge-SimpliSafePlatform/blob/b7ab75982fcc16b2bcedc1338f4699f6c2d3bc74/index.js#L146 should be 
`sensors[sensor]`

Also the line 144 https://github.com/graanco/homebridge-SimpliSafePlatform/blob/b7ab75982fcc16b2bcedc1338f4699f6c2d3bc74/index.js#L144 for me  accessory.context.SerialNumber was undefined so instead I used `accessory.getService(Service.AccessoryInformation).getCharacteristic(Characteristic.SerialNumber).value.toString()` instead.

With those, updating seems to work for me.

**Comment by graanco** [comment]
Merged
