### ISSUE TITLE
Home App Shows 'Arming...' When Alarm Set to 'Off'

### ISSUE THREAD

**Issue by nikonratm** [graanco/homebridge-SimpliSafePlatform#13]
Was having an issue where the Home app would show "Arming..." forever, looks related to using an incorrect constant (should be DISARM not DISARMED) on line 123 on index.js. Will submit PR.

<img width="176" alt="Screen Shot 2019-07-16 at 12 22 47 PM" src="https://user-images.githubusercontent.com/4887959/61324956-78977380-a7c8-11e9-8dc6-ddf8f975c245.png">

For reference, the constants are:
```
Characteristic.SecuritySystemTargetState
STAY_ARM: 0
AWAY_ARM: 1
NIGHT_ARM: 2
DISARM: 3

Characteristic.SecuritySystemCurrentState
STAY_ARM: 0
AWAY_ARM: 1
NIGHT_ARM: 2
DISARMED: 3
ALARM_TRIGGERED: 4
```

**Comment by graanco** [comment]
Nice
