### ISSUE TITLE
404 on npm install

### ISSUE THREAD

**Issue by bdjessup** [graanco/homebridge-SimpliSafePlatform#16]
Error is as follows:

```
npm ERR! code E404
npm ERR! 404 Not Found: homebridge-SimpliSafePlatform@latest
```

**Comment by graanco** [comment]
Okay??? Trying to install the product?

npm install -g homebridge-SimpliSafePlatform 
Should be the command....

**Comment by graanco** [comment]
I notice the same error today.. I would guess you need to use all lowercase... That is something new..

**Comment by nikonratm** [comment]
I created a [PR](https://github.com/graanco/homebridge-SimpliSafePlatform/pull/20) to address this in the readme, then we can close.
