### ISSUE TITLE
Eventual Error 401

### ISSUE THREAD

**Issue by nikonratm** [graanco/homebridge-SimpliSafePlatform#17]
Not sure if others are experiencing this but things are humming along great for days and then eventually (randomly as far as I can tell) it stops working. Homekit doesnt notice any issue so using the controls doesnt actually change the alarm state. 

So far all I know is that [line 147 of api.js](https://github.com/graanco/homebridge-SimpliSafePlatform/blob/a9cafbd17ad5ed1ea5631d3b20430141be3c123b/client/api.js#L147) starts logging
`Get_System 401`

It seems to happen right after a (failed?) call to `_Refresh_Access_Token`. Im working on a couple of ideas to fix (which is tough since I basically just have to wait days) but putting this out there...

**Comment by graanco** [comment]
Only thing I can think of maybe the time needs to be lowered for the refresh token refresh.... I asked the original create of the code questions about this and he seems unaffected...

**Comment by graanco** [comment]
I am surprised that this didn't come up

if (resp >= 400) throw('Access Forbidden. Please wait an hour and try again. Error: ', resp);

**Comment by graanco** [comment]
LOL did you see the code there is two awaits right about it...

**Comment by nikonratm** [comment]
Oh yea I noticed the two awaits and I fixed that in my local version (haven't submitted PR yet) and that didn't seem to change anything. The issue is actually happening again already, usually takes longer.

I think the error is thrown its just the syntax is wrong (e.g. should be `throw("..." + resp)` instead of `throw("..." , resp)` ?). But regardless of the error, the client will still keep pinging at the same interval, its not like it does actually "wait an hour" and it never seems to successfully get out of that death spiral. 

I will try lowering the refresh timer to 30s (had it set to 15). We'll see...

**Comment by graanco** [comment]
so I had my timer at 30 but I don't know if it is my internet or the chamberlain code but the home bridge died... I change the refresh timer from 60 to 240..
_access_token_expire = Date.now() + ((resp.expires_in-240) * 1000); Lets see if the code holds now...

**Comment by graanco** [comment]
Weird with my fixes in place the code doesn’t seem to be arming the house. It reports that it is armed but I don’t see it armed on the app....

**Comment by nikonratm** [comment]
This sounds exactly like my issue. I think if you added some logging statements you’d see the same thing (401). It happened to me last night even with the 30 second interval (though it does seem less). It seems to work fine if you restart the service so I’m wondering if we add some kind of force refresh token or something like that?

**Comment by graanco** [comment]
Unfortunately Apple removed my access to the system in July. I will be looking for another solution soon on remote desk services.

**Comment by graanco** [comment]
But as a fix I am thinking that once the timer expires just log back on again with the permissions from the first log in... I will look to see if anyone else is having the same problem

**Comment by graanco** [comment]
Do you think this line is messed up and not working
if (_access_token_expire && Date.now() >= _access_token_expire && !this._actively_refreshing)

**Comment by graanco** [comment]
But as a fix I am thinking that once the timer expires just log back on again with the permissions from the first log in... I will look to see if anyone else is having the same problem

Okay I did some small changes... I am not sure it is going to work... But copy and paste the api... Give it a try.

**Comment by nikonratm** [comment]
Hmm, not sure about the changes you made (probably shouldn't be committing them before we've tested) but I think I have a fix for this. Basically when we catch the error I just change the global variables to force a token refresh the next time around, this seems to work for me.

See PR above ( #18 )

**Comment by graanco** [comment]
Interesting I let it ride for a bit here and I see this
(node:2326) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'webapp' of undefined
    at API.request (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:248:39)
    at API.get_System (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:134:27)
    at API.get_Alarm_State (/usr/local/lib/node_modules/homebridge-simplisafeplatform/client/api.js:103:23)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:102:14)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)


looks like it loose the APIConfig data... that is very curious

**Comment by nikonratm** [comment]
I think that’s from your recent commits. My suggested changes were using code without those

**Comment by graanco** [comment]
I think I might have figured it out.... So here it is, System is up and running then the ISP looses connection or IP address changes. Once that happens the system goes to a 401 since this wasn't registered with simplisafe webapp website.

I am not so I changed the lines to have it try to authenticate again to simplisafe using user name and password.

**Comment by nikonratm** [comment]
Hmm, if you look at the [PR](#18) I submitted above it forces a _Refresh_Access_Token on the next "tick" which seems to me a cleaner solution than directly calling _Authenticate and I'm not sure if you really do need to call APICFGS again? I haven't tried your suggestion but with mine I've seen it run into a 401 and then recover successfully, it also doesn't require storing the password or anything like that. But its only been a day or so with my solution, not sure if it'll eventually stop working.

**Comment by graanco** [comment]
I figured that the refresh token would fail too since it is associated with the ip. So total reset to the authentication would be needed.

**Comment by graanco** [comment]
So does it work?? Which direction do you suggest we take... Just use the refresh token?

**Comment by nikonratm** [comment]
My solution works for me so far, yea, and seems to recover from this problem. Its your call if you want to merge my [PR](https://github.com/graanco/homebridge-SimpliSafePlatform/pull/18) or use your fix.

**Comment by graanco** [comment]
I used the pull for readme... and I used the self fix... I think that was the major issue. Yet, I don't think the 400 area fix was in the right place. I put it in the response area.  I hope this fixes it. Next up add in the cameras. The code is there we just need to make it work....
