### ISSUE TITLE
SimpliSafe shows up in HomeKit but cannot control and no sensors

### ISSUE THREAD

**Issue by brettonw** [graanco/homebridge-SimpliSafePlatform#19]
- MacOSX 10.14.6
- Node 12.9.1
- I have an older SimpliSafe alarm system, it's not the newest version of the base station.
- The WebApp and iOS app work just fine, I'm paying for the API level of service.
- The Homekit accessory reflects the state of my alarm, but I cannot control it and no sensors show up. I can change it from a keypad or the app, and Homekit will reflect that change.
- Per previous issues, I double and triple checked that my SerialNumber is correct in ~/.homebridge/config.json. 

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-simplisafeplatform",
            "name": "SimpliSafe",
            "SerialNumber": "######",
            "username": "xxx@xxx.xxx",
            "password": "xyxyxyxy",
            "refresh_timer": "60"
        }
    ]
}
```

**Comment by nikonratm** [comment]
Pretty sure this version of platform only works with SS3 e.g. the newest version of the hardware: https://github.com/graanco/homebridge-SimpliSafePlatform/issues/9#issuecomment-510108801

**Comment by graanco** [comment]
About a month ago, I removed the ability for SS2 and Original Systems. The way the system works you would get the message voice prompt not he system about updating and there is no way to turn it off. Sorry

**Comment by murphmr** [comment]
Try using chowielin's project as it works great with SS2. Allows you to arm and disarm at least. https://github.com/chowielin/homebridge-simplisafe-security-system.git

**Comment by brettonw** [comment]
I suggest updating the README to reflect SS version compatibility (and the new all lowercase requirements).

**Comment by brettonw** [comment]
Actually, chowielin's project is also SS#. It is forked from https://github.com/fholgado/homebridge-simplisafe-security-system, which stopped at SS2 support and works well for enabling and disabling the alarm.

**Comment by nikonratm** [comment]
Good suggestions about readme, I created a [PR](https://github.com/graanco/homebridge-SimpliSafePlatform/pull/20) to address this.
