### ISSUE TITLE
Cannot read property 'alarmState' of undefined

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#2]
(node:1344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'alarmState' of undefined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:269:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1344) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isAlarming' of undefined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:224:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by graanco** [comment]
Ouch that was a typo. I uploading a new version. I hope this one is the magic one...

**Comment by murphmr** [comment]
No magic yet - same issue it still appears. I completely uninstalled and reinstalled the plugin.

A couple of items to note - When I install the package using: npm install -g git+https://github.com/graanco/homebridge-SimpliSafePlatform.git

I have to change to lowercase to do the update. 
 npm --no-update-notifier install --unsafe-perm homebridge-simplisafeplatform@latest

Probably unrelated but thought I should mention it. Thanks for sticking with me on this.

Error is still the same:

(node:44957) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'alarmState' of undefined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:276:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44957) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44957) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isAlarming' of undefined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:226:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44957) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

**Comment by graanco** [comment]
Oh get it from npmjs not here... I haven’t updated here yet....

**Comment by graanco** [comment]
How goes it???

**Comment by murphmr** [comment]
Still at the same point with the error noted on the 1.0.18 version.

**Comment by graanco** [comment]
I am off to get a new MacBook I’ll try it there

**Comment by graanco** [comment]
my recommendation is to do a 
sudo npm uninstall -g homebrdige-simplisafeplatform
sudo npm install -g homebrdige-simplisafeplatform

That way it is installed correctly??? I just applied 1.0.19 and it does the correct version check now.... nodes needs to be 12.4 or greater and homebridge is 0.4.5 or greater.

**Comment by murphmr** [comment]
Is the package published? I get an error when trying to install from npm:
sudo npm install -g homebrdige-simplisafeplatform
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebrdige-simplisafeplatform - Not found
npm ERR! 404 
npm ERR! 404  'homebrdige-simplisafeplatform@latest' is not in the npm registry.
npm ERR! 404 **You should bug the author to publish it (or use the name yourself!)**
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by murphmr** [comment]
Typo in the package name above. 
> sudo npm uninstall -g **homebridge-simplisafeplatform**
> sudo npm install -g **homebridge-simplisafeplatform**

**Comment by murphmr** [comment]
So just an update - I completely uninstalled homebridge, all my plugins, deleted my .homebridge directory and did a clean install of homebridge and my plugins. Previously I had the permissions wrong on the node_modules directory so I took this opportunity to clean that up as well. 

Unfortunately, this didn't seem to help with the "toString" error above as I am still getting that after the install.

**Comment by murphmr** [comment]
Ok so progress - apparently somewhere along the line my password dropped out of the config.json - after I added that back in the "Missing System Data" went away and a couple of accessories loaded. 
A new error - I will open a new case for that one. 

So just to re-iterate:
Missing System Data = missing userid or password....
AlarmState issue looks to have been corrected by re-installing homebridge

**Comment by murphmr** [comment]
So just a note here - it seems that the password is automatically removed from the config file when the refresh_token is added to the config file.

**Comment by graanco** [comment]
Yes, I was getting the same error too.... I wonder if the refresh token isn't updating correctly... line 276 and 229
