### ISSUE TITLE
1.2.2 issue finding platform

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#22]
### **During the install:**
 npm --no-update-notifier install --unsafe-perm homebridge-simplisafeplatform@latest

> @ffmpeg-installer/darwin-x64@4.1.0 postinstall /usr/local/lib/node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/darwin-x64
> chmod u+x ffmpeg

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-x64@4.1.0 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/win32-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-x64@4.1.0: wanted {"os":"win32","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"darwin","arch":"x64"})

+ homebridge-simplisafeplatform@1.2.2
added 1 package from 1 contributor and updated 1 package in 4.774s

### **When trying to start:**
[9/15/2019, 10:52:00 PM] Loading 2 platforms...
[9/15/2019, 10:52:00 PM] **Error: The requested platform 'homebridge-simplisafeplatform' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)**
[9/15/2019, 10:52:00 PM] Got SIGTERM, shutting down Homebridge...

### **Here is my config.json for platforms:**
platforms": [
        {
            "platform": "homebridge-simplisafeplatform",
            "name": "SimpliSafe Client",
            "SerialNumber": "0000A1234",
            "username": "email@redacted",
            "password": "passwordredacted",
            "refresh_timer": "30"
        },
        {
            "name": "Config",
            "port": 8181,
            "auth": "form",
            "theme": "dark-mode",
            "tempUnits": "f",
            "sudo": false,
            "platform": "config"
        }
    ]

**Comment by murphmr** [comment]
So to fix this: I installed ffmpeg and then installed the updated simplisafeplatform module:
npm install --save @ffmpeg-installer/ffmpeg
npm --no-update-notifier install --unsafe-perm homebridge-simplisafeplatform@latest

**Comment by graanco** [comment]
Good to know it’s up... when I get to the v3 house I will look more into the socket-Io. I wonder why the app didn’t pull the ffmpeg too
