### ISSUE TITLE
Contact sensors not getting status updates

### ISSUE THREAD

**Issue by murphmr** [graanco/homebridge-SimpliSafePlatform#24]
I noticed with versions 1.2x that the contact sensors are no longer accurately reflecting the sensor status. All my contact sensors show the status as closed even when they are open and have been open for some time. I tried resetting, reinstalling and re-adding the homebridge accessory all together. I also changed the refresh interval from 30 to 60 but that doesn't seem to make a difference. Not sure it it is a SS3 issue specifically.

**Comment by graanco** [comment]
I was wondering about this... I will fix that shortly... Sorry I was hoping that the socket.io would push that... I guess I need to put back in a scrap for that.... how many versions ago did I have that is there??

**Comment by murphmr** [comment]
I think 1.1.1 is the last version that it was still working.

**Comment by graanco** [comment]
Okay... I think I have it going now... please give it a try. I have added temp sensor onto the alarm system if you have a temperature sensor in the system. If I remember right it shows up in the arming area of the alarm. And I have motion detector added to the camera... I need a little feed back I dump data out if the camera records motion... I need a copy of that... Or did you already send it to the other guy?

**Comment by graanco** [comment]
Oh I see it in the other traffic. great.. I will make it work!!

**Comment by murphmr** [comment]
Also about once an hour the system is getting a disarm signal even though I didn't disarm the system this is new since the update.

**Comment by graanco** [comment]
Yes, I noticed the same here... it is the websocket... I think your getting an console log?

**Comment by murphmr** [comment]
Yes:
(node:734) UnhandledPromiseRejectionWarning: ReferenceError: sensor is not defined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:221:124
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 180)
[10/9/2019, 11:28:48 AM] [SimpliSafe Client] {
  eventTimestamp: 1570638524,
  eventCid: 1407,
  zoneCid: '0',
  sensorType: 0,
  sensorSerial: '',
  account: '0000abcd',
  userId: 200000,
  sid: 100000,
  info: 'System Disarmed by Remote',
  pinName: '',
  sensorName: '',
  messageSubject: 'SimpliSafe System Disarmed',
  messageBody: 'System Disarmed: Your SimpliSafe security system was disarmed by Remote at Address on 10-9-19 at 11:28 am',
  eventType: 'activity',
  timezone: 1,
  locationOffset: -300,
  internal: { dispatcher: 'cops' },
  senderId: 'wifi',
  eventId: 6548571787,
  serviceFeatures: {
    monitoring: true,
    alerts: true,
    online: true,
    video: false,
    hazard: false
  },
  copsVideoOptIn: true,
  video: {
    ff7b75cbdf8fba5d6f1c617000001f0c: {
      clipId: 2268707379,
      preroll: 5,
      postroll: 20,
      cameraName: 'Main'
    },
    '8a8b7ee0b9308c4dcc1fdb04f0001f04': {
      clipId: 2268707381,
      preroll: 5,
      postroll: 20,
      cameraName: 'Front'
    },
    f8034ea929a993901f627838e005cf33: {
      clipId: 2268707383,
      preroll: 5,
      postroll: 20,
      cameraName: 'Basement'
    },
    af27a19154ad458e03ece62ff00a6367: {
      clipId: 2268707401,
      preroll: 5,
      postroll: 20,
      cameraName: 'Front Door'
    }
  }
}
(node:734) UnhandledPromiseRejectionWarning: ReferenceError: sensor is not defined
    at /usr/local/lib/node_modules/homebridge-simplisafeplatform/index.js:221:124
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by graanco** [comment]
I see the error on line 221 I will fix now... Also I reverted back a lot to the websocket... I wish they pushed temp status and contact status... That way I could remove the pull (webpage scrapping) and used their push mechanism.

**Comment by graanco** [comment]
Version 1.2.9 is up and should fix all this... I am trying to get Secret Alerts to work but HK has an issue with push notifications. It only also statically built ones. I hope I got the settings right.

**Comment by murphmr** [comment]
No errors as of yet but the contact sensors are not updating.

**Comment by graanco** [comment]
Change line 207... 

if ([ss.ssDeviceIds.entrySensor, ss.ssDeviceIds.freezeSensor].includes(sensor.type)) {

Oops that was my bad using HK terminology verse SS

**Comment by graanco** [comment]
Tell how it goes and I will publish again if it okay

**Comment by murphmr** [comment]
Yes that fixed it - contact sensors updating and no errors.

**Comment by graanco** [comment]
Okay I pushed the ...10 update. I hope this does fix things. I also played with the camera setting too. Maybe just maybe....

**Comment by murphmr** [comment]
1.2.10 fixed this. Thanks!!!!

**Comment by graanco** [comment]
How about the camera issue... The other guy had it so the video pull was the same as the request.... I set it up so the SS Cam setting took the request with its info and device video get what it is asking for. Also if you change the settings between restarts it pulls the current settings too. All about the bandwidth the end user has.

**Comment by murphmr** [comment]
Seems I can't view any quality video now, not even 480 which was working.

**Comment by graanco** [comment]
Wow I found an issue with arming. Even the. Other. Guy. Might have it. I’ll pstcode

**Comment by graanco** [comment]
I've GitHub posted 1.2.22. I am hoping the camera issue is fixed.
