### ISSUE TITLE
Duplicates of all sensors.

### ISSUE THREAD

**Issue by calebcaudill** [graanco/homebridge-SimpliSafePlatform#25]
Loaded it up and there are two of each one of my contact sensors, motion sensors, and two alarms showing. I should have 9 accessories but it's showing 18. Currently, solving the problem by not including the dupes in my favorites and putting them to the default room but would be nice to completely get rid of them.

**Comment by graanco** [comment]
Interesting... Sorry for my delay...  Shutdown Homebridge then go into the ~./homebridge folder and delete the accessories folder there... restart and it should fix that issue. If it shows again Ill have to look more into this.

**Comment by graanco** [comment]
Any luck?

**Comment by calebcaudill** [comment]
Worked perfect! Thank you :)
