### ISSUE TITLE
Supported accessories

### ISSUE THREAD

**Issue by afalahi** [graanco/homebridge-SimpliSafePlatform#26]
This is not an issue or problem with the module, but I didn’t know where else to ask questions. Are all accessories supported? Lock, bell, motion sensors etc? Thanks for the great work!

**Comment by nikonratm** [comment]
I know what you mean about not having anywhere else to ask questions, but FWIW your question is answered in the README (on the homepage).

**Comment by graanco** [comment]
This system supports all the stuff I have... SS door locks temperature smoke co2 leak etc. Yet on the Cell only systems there will be a message on it saying “Your system has been synchronized”. I stuffed my base in a closet to stop hearing that message. I was thinking on adding an option for those systems to allow a config setting to turn it off if the end user would like.  So when that is off you will not get a message but still get notifications when you open a contact sensor when the system is armed and it will support automation.

**Comment by graanco** [comment]
> I know what you mean about not having anywhere else to ask questions, but FWIW your question is answered in the README (on the homepage).
> 
> EDIT: Sorry I thought I was commenting in another project (I used to contribute to this SS Homebridge plugin but now contribute to [another one](https://github.com/nzapponi/homebridge-simplisafe3), which for the record does support that stuff, I think this one does too but I'll let the author weigh in)

Unfortunately that other system last I knew doesn’t support cell versions or co2/smoke alerts. I asked him to use the socket.io to do it and he refused. Up to you.

**Comment by afalahi** [comment]
Thank you! So your module supports the missing accessories from the other module (motion censor etc) that’s great, and thanks for your prompt response!

**Comment by nikonratm** [comment]
@graanco does your system support motion sensors even when the system is not armed? My understanding was that the SS API doesn’t provide any events for those unless the system is armed?

**Comment by afalahi** [comment]
Honestly idk. I haven’t received my unit yet, so I’m trying to make sure I use the right module. You maybe right though, I wanted to leverage motions sensors for things like turn outside lights etc, but I might get a motion sensing light or eve sensor. Thanks for the clarification

**Comment by nikonratm** [comment]
Sorry I was asking the author @graanco If things had changed

Last we looked into this the motion sensors only worked when the system is armed which is why we left them out of our plugin, it seemed misleading because most people would want to do exactly what you describe eg create automations). Wasn’t sure if @graanco found a way to do it (unfortunately I don’t think so)

**Comment by graanco** [comment]
> Sorry I was asking the author @graanco If things had changed
> 
> Last we looked into this the motion sensors only worked when the system is armed which is why we left them out of our plugin, it seemed misleading because most people would want to do exactly what you describe eg create automations). Wasn’t sure if @graanco found a way to do it (unfortunately I don’t think so)

Your are right all the socket.io sensors work when the system is armed to inform you the alerts. Yet that can be change via the hidden event messages. I verified that on the cell only systems since I can edit that on those through the website still. I am not really sure on the settings for version 3. I did think about adding that hidden event commands alerts via the api for all the systems.  Maybe a switch to add in the config to have that set up.

**Comment by afalahi** [comment]
> > Sorry I was asking the author @graanco If things had changed
> > Last we looked into this the motion sensors only worked when the system is armed which is why we left them out of our plugin, it seemed misleading because most people would want to do exactly what you describe eg create automations). Wasn’t sure if @graanco found a way to do it (unfortunately I don’t think so)
> 
> Your are right all the socket.io sensors work when the system is armed to inform you the alerts. Yet that can be change via the hidden event messages. I verified that on the cell only systems since I can edit that on those through the website still. I am not really sure on the settings for version 3. I did think about adding that hidden event commands alerts via the api for all the systems. Maybe a switch to add in the config to have that set up. The cameras as you do know have alerts with certain setting enabled on the api for socket.io events. Also the cameras have there own event messaging too for their status.

So you don’t have SS3? It seems like your module might support more sensors atm so I’ll give it a try. Thank you both for your hard work to make this a possibility on HomeKit!

**Comment by graanco** [comment]
Yes I own both systems. One is monitoring a house that I can only go home to on the weekends. So I work with the cell version more often.

**Comment by afalahi** [comment]
I’m sorry I’m back lol. Last question (my system is delayed so idk what else todo) will this module be essential expose the different accessories so i can ask Siri to lock my door, or have the door unlock when I’m home? Or am i better off with the august lock

**Comment by graanco** [comment]
Personally I like the SimpliSafe lock. I haven't worked with the August Locks yet (I don't like the choices of the colors for ss) but in SS the system can be setup up to control the door lock with different alarm settings. Mine when armed door is locked when off it is unlocked. One thing I had to do make a note. I had mine setup backwards at first had to go to the keypad to perform recalibrate to make it respond correctly.
