### ISSUE TITLE
Cameras no response

### ISSUE THREAD

**Issue by afalahi** [graanco/homebridge-SimpliSafePlatform#27]
the log shows FFmpeg exited with code 1. Not using IPV6 afaik I have it disabled on my router

**Comment by afalahi** [comment]
I tried to turn on debug mode, but it's not showing additional details, everything else in this plugin works great! better than the other plugins. just the doorbell video never shows. I read other issues that discussed changing the resolution, and I did that but nothing change. rebooted HB but still nada

**Comment by graanco** [comment]
That is the one item I don’t have yet!! But with that being said. You did debug=* homebridge-D

**Comment by afalahi** [comment]
Oh I definitely didn’t run that command. I’m using homebridge on docker with the UI plugin. So youre saying to stop HB, SSH to my docker, and run HB with the debug args to get the debug output

**Comment by nikonratm** [comment]
I’ve read reports of people having trouble with ffmpeg with docker. Btw, I have video doorbell on my system.

**Comment by afalahi** [comment]
Oh that sucks then, i could get a raspberry pie to fix the issue i guess

**Comment by graanco** [comment]
I have a Mac mini running as a server at the house. It serves the media for the home... and it works fine.  I am glad for the help. I didn’t know the docker ffmpeg issue. I will add it to the readme

**Comment by nikonratm** [comment]
I don’t know if it’s impossible I’ve just seen people having issues, I’ve never looked into too deeply because I don’t use docker

**Comment by afalahi** [comment]
How do I run homebridge in debug mode but still point it to the config file? I launched HB in insecure mode and said camera rtp stream not supported :/ If you don't think there is a fix/too much effort then feel free to close this :(

**Comment by kaicherry** [comment]
I figured out what this issue is on Raspberry Pi. I'm using a buster-lite image.

Basically,the linux-arm variant in @ffmpeg-installer segfaults; no longer works.

As a workaround, try these steps:

1. sudo apt-get update
2. sudo apt-get install ffmpeg
3. sudo cp /usr/bin/ffmpeg /usr/local/lib/node_modules/homebridge-simplisafeplatform/node_modules/@ffmpeg-installer/linux-arm/

This should get your cameras back up and running.
