### ISSUE TITLE
URL is not defined

### ISSUE THREAD

**Issue by carlmiller99** [graanco/homebridge-SimpliSafePlatform#3]
So I'm a noob ... but I haven't been able to figure this error out.
I suspect its something I'm doing wrong, but any insight much appreciated.
This is a fantastic project. I appreciate you.
SS3 / 24.99

[2019-6-13 22:46:46] [SimpliSafe] Up and monitoring.
[2019-6-13 22:46:46] Homebridge is running on port 51826.
(node:1866) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at API.Promise (/usr/lib/node_modules/homebridge-simplisafeplatform/client/api.js:68:42)
    at new Promise (<anonymous>)
    at new API (/usr/lib/node_modules/homebridge-simplisafeplatform/client/api.js:66:5)
    at new SimpliSafe (/usr/lib/node_modules/homebridge-simplisafeplatform/index.js:23:10)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
(node:1866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1866) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at API.apiconfig (/usr/lib/node_modules/homebridge-simplisafeplatform/client/api.js:83:38)
    at SimpliSafe.<anonymous> (/usr/lib/node_modules/homebridge-simplisafeplatform/index.js:48:14)
    at emitNone (events.js:106:13)
    at API.emit (events.js:208:7)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:103:13)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
(node:1866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by graanco** [comment]
This is the line at is causing you issues....
var resp = await webResponse(new URL('https://webapp.simplisafe.com/ssAppConfig.js'), {METHOD: 'GET'});

You can see if the url works for you copy this is a browser https://webapp.simplisafe.com/ssAppConfig.js and see if it pull up the data. Firefox seems to show and IE seems to download it.

Beyond this it makes me wonder about if everything is installed correctly...
In order for this to work you will need NODEJS installed and homebridge, I have installed this on MAC OSX and Windows systems and it appears to be fine.

Depending on your system follow the wiki pages for installation from this link.
https://github.com/nfarina/homebridge/wiki

installing the plugin should be done by

npm install -g homebridge-simplisafeplatform

If you had already done this the products might out of date...

npm update command usually gets it all updated.

After that make sure the config.json is set up correctly
by my example for on github or npmjs

Make sure you change your email and password. 

 Then just run homebridge

After you use the product for the first time the password will be replace in the config.json file to help you out with security.


Lastly, I am looking into simplisafe API a little more there might be a version 1.1 change in the near future.

**Comment by carlmiller99** [comment]
Thank you for your response, graanco

I agree that is the line causing the problem.  Just cannot figure out why...

In my browser it returns:

;(function(g){"use strict";if(typeof g.simplisafe==='undefined'){g.simplisafe={};}g.simplisafe.webapp={};
var a=simplisafe.webapp;
a.apiHost="https://api.simplisafe.com";
a.apiPath="/v1";
a.mediaHost="https://media.simplisafe.com";
a.mediaPath="/v1";
a.simpliSafeUrl="https://simplisafe.com";
a.nestAuthUrl="https://home.nest.com/login/oauth2?client_id=55db4458-e3a2-4300-afd7-d1287dbe21b2&state=STATE";
a.nestFirebaseUrl="wss://developer-api.nest.com";
a.augustAuthUrl="https://auth.august.com/authorization?client_id=6c7dda55-11c4-43ea-9d4a-fb95bd17bf55&state=STATE&redirect_uri=REDIRECT_URI";
a.chaseNaHpfIFrameUrl="https://www.chasepaymentechhostedpay.com/hpf/1_1";
a.chaseEuDhppIFrameUrl="https://ppipe.net/hpp/web/DoPay";
a.useGaTrackingId=true;
})(window);

I am running node.js and Homebridge on a raspberry pi.  It was all a fresh install, should be up to date.

My config.json validates and is:

{
	"bridge":
	{
		"name": "Homebridge",
		"username": "CD:22:3D:E3:CE:31",
		"port": 51826,
		"pin": "734-45-155"
	},
	"platforms": [
	{
		"platform" : "homebridge-simplisafeplatform",
		"name" : "SimpliSafe",
		"SerialNumber": "withheld",
		"username" : "carlmiller9@gmail.com",
		"password" : "withheld",
		"refresh_timer": "10"
	}
	]
}

I will try updating everything and try a fresh install if that doesn't work.

If you see any issues with the above, your insight is appreciated.

Thanks again for your work on this awesome project!

**Comment by graanco** [comment]
Okay I change the requirements on the system to ensure you are running same version of NODEJS and homebridge. That error you get tells me that NodeJS is out of date. You need to be at least on version 12.4 or greater.... https://nodejs.org/api/url.html

**Comment by carlmiller99** [comment]
You are 100% correct. I was on 8.x. Oops.
Updating did fix the URL error.

I also updated to 1.0.19 with:
sudo npm uninstall -g homebridge-simplisafeplatform
sudo npm install -g homebridge-simplisafeplatform

However, now I see this error:

[6/15/2019, 2:16:17 PM] [SimpliSafe Client] Up and monitoring.
[6/15/2019, 2:16:17 PM] Homebridge is running on port 51826.
(node:985) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getCharacteristic' of undefined
    at SimpliSafe.addAccessory (/usr/lib/node_modules/homebridge-simplisafeplatform/index.js:178:13)
    at /usr/lib/node_modules/homebridge-simplisafeplatform/index.js:83:20
    at Array.forEach (<anonymous>)
    at SimpliSafe.initPlatform (/usr/lib/node_modules/homebridge-simplisafeplatform/index.js:77:25)
    at /usr/lib/node_modules/homebridge-simplisafeplatform/index.js:61:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

Thank you so much for your help with this. I'd like to buy you a beer! Im also SUPER excited about v1.1 !!  :-D

**Comment by graanco** [comment]
found it change line 177 to accessory.getService(Service.LeakSensor) not accessory.getService(Service.ContactSensor) in the index.js file. I'll update it soon.

**Comment by carlmiller99** [comment]
You are the man. Am away from my pi for a few days but will try this change as soon as Im back home. Thank you.

**Comment by graanco** [comment]
Also found the issue with the CO2 line too.. Fixed an updated it.

**Comment by graanco** [comment]
Yes there was definitely a refresh token issue.... I hope I fixed it...

**Comment by carlmiller99** [comment]
Works! All sensors exposed! Genius
