### ISSUE TITLE
You need to be at least on version 12.4 or greater.... https://nodejs.org/api/url.html

### ISSUE THREAD

**Issue by hubartt** [graanco/homebridge-SimpliSafePlatform#5]
So, I've just set up a Raspberry Pi with Hoobs 2 (an out of the box homebridge system). As you can see here at this link - Hoobs runs the latest LTS version of Node. Curious what options I may have to get these 2 playing nicely?

https://www.reddit.com/r/homebridge/comments/c01vgh/hoobs_homebridge_out_of_the_box_version_200_out/

Okay I change the requirements on the system to ensure you are running same version of NODEJS and homebridge. That error you get tells me that NodeJS is out of date. You need to be at least on version 12.4 or greater.... https://nodejs.org/api/url.html

_Originally posted by @graanco in https://github.com/graanco/homebridge-SimpliSafePlatform/issues/3#issuecomment-502383815_

**Comment by graanco** [comment]
Yes, I set up the system to use NodeJS on 12.4. Since I use all the current features... I could drop it down to 10.16.0 which the website says most users use... Yet, I think I might be using higher programming style and API.

**Comment by murphmr** [comment]
a good guide for updating node on a Mac: 
https://bytearcher.com/articles/ways-to-get-the-latest-node.js-version-on-a-mac/

**Comment by graanco** [comment]
I just go to NodeJS.org and download the app to install it... too simple.

**Comment by graanco** [comment]
okay I think I am going to remove SS2 or less support... The delay is causing a response issue. Also I will be setting it up so there is a 30 second loop for the alarm status unless I can get the push working from socket.io

**Comment by graanco** [comment]
Updated closing this issue...
