### ISSUE TITLE
Temperature sensor showing 32deg F

### ISSUE THREAD

**Issue by muzzymate** [graanco/homebridge-SimpliSafePlatform#6]
Just got your wonderful Homebridge plugin installed and working. Incredibly thankful, especially since Simplisafe appears to be backing down from their promised native Homekit support.

First issue I've noticed is that my basement Simplisafe temperature sensor (only one I have) is showing 32 degrees fahrenheit in the Home app while the Simplisafe app shows a more reasonable 67 degrees.

**Comment by graanco** [comment]
That is weird. It appears to work...

**Comment by graanco** [comment]
Are you reporting in C or F? Also, is this on a V3 system. My v2 seems to report fine.

**Comment by muzzymate** [comment]
I have a version 3 Simplisafe system. Both the Simplisafe and Home app reports in F.  Let me know if there are any log files or output that might assist. 

In case it helps narrow down, I have some other Nest temperature sensors, hosted on a different Homebridge instance, that report expected temperatures in fahrenheit in the Home app. On the same instance as the Simplisafeplatform plugin, I have a Weather plugin that outputs expected fahrenheit temperatures.

**Comment by graanco** [comment]
Thank you... I found it. Pushed it out. I hope it work. I don't have a V3 temp sensor.

**Comment by muzzymate** [comment]
Unfortunately, after upgrading to version 24, the temperature sensor is still reporting in Home as 32 degrees fahrenheit, rather than the current expected 66 deg F. I also attempted an accessory reset just in case. I am viewing it from both the macOS Mojave 10.14.5's Home app as well as iOS13b2's Home app.

**Comment by graanco** [comment]
LOL I reversed the sensors functions between v3 and v1/2... It works again on the V1/2 system try it again... 1.0.26

**Comment by muzzymate** [comment]
Yes, this corrected the issue. My version 3 temperature sensor is now reporting the correct value in the Home app.

**Comment by graanco** [comment]
Well, I found one message I am able to send just to you. I've updated the GitHub repo. And wonder if the camera issue for you is fixed. I rewrote a lot on this...
