### ISSUE TITLE
Missing System Data / Cannot read property 'toString'

### ISSUE THREAD

**Issue by carlmiller99** [graanco/homebridge-SimpliSafePlatform#8]
I'm seeing this error intermittently. Does not crash the homebridge process, but does seem to affect responsiveness:

Missing Sytem Data
(node:1096) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/homebridge-simplisafeplatform/index.js:229:32
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Missing Sytem Data
(node:1096) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/homebridge-simplisafeplatform/index.js:276:32
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Any thoughts? 

I appreciate your work on this project. Still excited for v1.1 too!

**Comment by murphmr** [comment]
Missing system data means that you need to re-enter the password in the config.json file. I opened an issue on this as I have had to re-enter mine daily to keep things working.

**Comment by carlmiller99** [comment]
Hmmmmm. Interesting then that it can recover from this error and resume normal operation without either restarting the process OR changing the config.json...

**Comment by graanco** [comment]
I get the same issue. It looks like that SS change the way the token API login work... I am going to review some other code out there but first I will update the code to remove that area today.

**Comment by carlmiller99** [comment]
sounds good! will keep an eye on npm for that

**Comment by carlmiller99** [comment]
p.s. you should consider adding a sponsor button so your fans can help support this project

**Comment by carlmiller99** [comment]
Resolved ... closing
